### PR TITLE
Astyle Changes 

### PR DESCRIPTION
**Pull request by henrytran28**
Added travis, astylerc and modified format.sh

---
This change is [Reviewable](https://reviewable.io/reviews/ucsolarcarteam/backupcamera/2)

### CODE REVIEW

**Comment by bseto** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwSdAL1Tun_xVZRrvg:-KTwSdAL1Tun_xVZRrvh:b-ubjmx5) (no related file):*
Good job! format.sh does what it is supposed to so that's good. 
Overall everything is pretty good. Only a few things that I think we should have a discussion about to see if we all agree on the style. 

---

*[astylerc, line 5 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwSow3ICC9WcbIVfDW:-KTwSow4IMWmBPf-cVfl:b-z84y6a) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/astylerc#L5)):*
> ```
> --style=allman
> # int Foo(bool isBar)
> # {
> ```

Do we want `{` be on the same line as `int Foo(bool isBar)`? 

---

*[astylerc, line 7 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwTM-3uDEHGVjnVOtY:-KTwTM-44fHWgUCc9bb9:b-s8f38b) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/astylerc#L7)):*
> ```
> # {
> #     if (isBar)
> #     {
> ```

This `{` is especially conflicting with Line 46

---

*[astylerc, line 70 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwTpBsYQYI40FecPbj:-KTwTpBsYQYI40FecPbk:b4dwxdi) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/astylerc#L70)):*
> ```
> 
> --align-pointer=type
> # char* foo1;
> ```

We should probably have a discussion for this. I'm okay with adopting to this style, but I do want to illustrate the problems that come with putting the `*` beside the type and not the variable name.

http://stackoverflow.com/questions/13894228/where-to-put-the-star-in-c-and-c-pointer-notation

@enoch, @bill. What do you guys think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2)*

**Comment by enochtsang** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[astylerc, line 5 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwSow3ICC9WcbIVfDW:-KTwu4eRcKT-MSma7akB:b-jc7fio) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/astylerc#L5)):*
<details><summary><i>Previously, bseto (Byron Seto) wrote…</i></summary>
> Do we want `{` be on the same line as `int Foo(bool isBar)`? 
</details>
No, I think it should be on the next line to match the heaps of telemetry code already done this way. This astylerc file is written by me, so any questions can be directed at me. The template file for this is located in the development guide.

---

*[astylerc, line 7 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwTM-3uDEHGVjnVOtY:-KTwu19_XIgSxjSAKGmh:b-ajixis) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/astylerc#L7)):*
<details><summary><i>Previously, bseto (Byron Seto) wrote…</i></summary>
> This `{` is especially conflicting with Line 46
</details>
It's not conflicting, it's just the example assumes a different brace style.

---

*[astylerc, line 70 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwTpBsYQYI40FecPbj:-KTwuKcLZI70eQWdNaQo:b91n0mb) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/astylerc#L70)):*
<details><summary><i>Previously, bseto (Byron Seto) wrote…</i></summary>
> We should probably have a discussion for this. I'm okay with adopting to this style, but I do want to illustrate the problems that come with putting the `*` beside the type and not the variable name.
> 
> http://stackoverflow.com/questions/13894228/where-to-put-the-star-in-c-and-c-pointer-notation
> 
> @enoch, @bill. What do you guys think?
</details>
I'm a much bigger fan of `int* bar;` where the intent is clear. Overall in our code it hasn't been common to declare many variables in a single line, I would advise against that anyways. That discussion is a good one that @bill should know about that though.

---

*[format.sh, line 10 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwukl6_rRht-duhW4z:-KTwukl6_rRht-duhW5-:b-bcxqdm) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/format.sh#L10)):*
> ```Shell
> 
> astyle "*.h" "*.c" -r --options=astylerc
> find $1 -name "*.orig" -delete
> ```

This project doesn't need to take in a directory argument. I told you about this that the Epsilon-Embedded-Software repo was a special case since there were many projects in one branch. Also this script doesn't really work, `astyle "*.h" "*.c" -r --options=astylerc` doesn't go into a specific directory. I fixed this in a commit in the Epsilon-Embedded-Software repo, but regardless this feature isn't necessary in this repo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2)*

**Comment by bill-luu** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[astylerc, line 5 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwSow3ICC9WcbIVfDW:-KTyyWISjzNn20pNKGEX:b-p2sfgy) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/astylerc#L5)):*
<details><summary><i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>
> No, I think it should be on the next line to match the heaps of telemetry code already done this way. This astylerc file is written by me, so any questions can be directed at me. The template file for this is located in the development guide.
</details>
Yeah, and up until now the style guide has specified the `{` be on the next line anyways.

---

*[astylerc, line 70 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwTpBsYQYI40FecPbj:-KTyyup7ZKYi576GuaHI:b-s1ccwe) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/astylerc#L70)):*
<details><summary><i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>
> I'm a much bigger fan of `int* bar;` where the intent is clear. Overall in our code it hasn't been common to declare many variables in a single line, I would advise against that anyways. That discussion is a good one that @bill should know about that though.
</details>
That is interesting! I'm fine with this style as well, although we should also specify in the guide that we discourage declaration of multiple variable in a single line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2)*

**Comment by bseto** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[astylerc, line 70 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwTpBsYQYI40FecPbj:-KU-3SQmQGP0k9flnpZJ:bd5a9vk) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/astylerc#L70)):*
<details><summary><i>Previously, bill-luu wrote…</i></summary>
> That is interesting! I'm fine with this style as well, although we should also specify in the guide that we discourage declaration of multiple variable in a single line.
</details>
Ok, yea that sounds good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2)*

**Comment by henrytran28** [comment]
*[format.sh, line 10 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwukl6_rRht-duhW4z:-KU04ueq-P7fnKv-53Em:b-yx1wxd) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/format.sh#L10)):*
<details><summary><i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>
> This project doesn't need to take in a directory argument. I told you about this that the Epsilon-Embedded-Software repo was a special case since there were many projects in one branch. Also this script doesn't really work, `astyle "*.h" "*.c" -r --options=astylerc` doesn't go into a specific directory. I fixed this in a commit in the Epsilon-Embedded-Software repo, but regardless this feature isn't necessary in this repo.
</details>
Okay so should I just change ./format.sh src to ./format.sh? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2)*

**Comment by henrytran28** [comment]
*[format.sh, line 10 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwukl6_rRht-duhW4z:-KU06s4AeSZav-PtvpWC:b-t2ro4a) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/format.sh#L10)):*
<details><summary><i>Previously, henrytran28 (Henry Tran) wrote…</i></summary>
> Okay so should I just change ./format.sh src to ./format.sh? 
</details>
I noticed your changes. I will use that moving forward. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2)*

**Comment by enochtsang** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[format.sh, line 10 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwukl6_rRht-duhW4z:-KU0nbNsXGqkUMQd_IuD:b-ucm42d) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/format.sh#L10)):*
<details><summary><i>Previously, henrytran28 (Henry Tran) wrote…</i></summary>
> I noticed your changes. I will use that moving forward. 
</details>
This project doesn't need to take in a directory argument. I told you about this that the Epsilon-Embedded-Software repo was a special case since there were many projects in one branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2)*

**Comment by henrytran28** [comment]
*[format.sh, line 10 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwukl6_rRht-duhW4z:-KU069GDU2R64v6myR_J:b16u9gg) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/format.sh#L10)):*
> Okay so should I just change ./format.sh src to ./format.sh? 
<details><summary><i alt="summary">Quoted 109 lines of code…</i></summary>
>               
>               
>                 
>                   4 minutes ago
>                 
>               
>             
>           
>         
>         
>           
>             
>               
>                 
>                   
>                   
>                 
>               
>               
>                 bill-luuis:
>                 
>                 
>                    Following: following new comments, but neutral on resolving.
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>               
>             
>               
>                 
>                   
>                   
>                 
>               
>               
>                 enochtsang (Enoch Tsang)is:
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                 
>                    Blocking: not OK to resolve until disposition changed manually.
>                 
>                 
>                 
>                 
>               
>             
>             
>               
>                 
>                 
>               
>               
>               
>                 
>                   You are:
>                   
>                 
>                 
>                 
>                 
>                 
>                 
>                   
>                   
>                   Discussing: OK to resolve only if acknowledged
>                   
>                   or OK'd
>                   last comment.
>                   (Currently: OK.)
>                   
>                 
>                 
>                    Satisfied: OK to resolve any time, and own comments don't require acknowledgement.
>                   
>                 
>                 
>                    Blocking: not OK to resolve until disposition changed manually.
>                 
>                 
>                    Withdrawn: dropped and resolved the discussion before it got started.
>                   
>                     This will resolve and hide the discussion.
>                   
>                 
>                 
>                 
>               
>             
>           
>           
>             
>               
>                 
>                   Done
>                 
>                 
>                 Thanks for clarifying</details>


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2)*

**Comment by henrytran28** [comment]
*[format.sh, line 10 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KTwukl6_rRht-duhW4z:-KU2ZEQV7s7lwVy2yS93:byip6zl) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/50aef63310a9912380bac652622bdd51066c5ea9/format.sh#L10)):*
<details><summary><i>Previously, henrytran28 (Henry Tran) wrote…</i></summary>
> > Okay so should I just change ./format.sh src to ./format.sh? 
> >               
> >               
> >                 
> >                   4 minutes ago
> >                 
> >               
> >             
> >           
> >         
> >         
> >           
> >             
> >               
> >                 
> >                   
> >                   
> >                 
> >               
> >               
> >                 bill-luuis:
> >                 
> >                 
> >                    Following: following new comments, but neutral on resolving.
> >                 
> >                 
> >                 
> >                 
> >                 
> >                 
> >                 
> >                 
> >                 
> >                 
> >               
> >             
> >               
> >                 
> >                   
> >                   
> >                 
> >               
> >               
> >                 enochtsang (Enoch Tsang)is:
> >                 
> >                 
> >                 
> >                 
> >                 
> >                 
> >                 
> >                 
> >                    Blocking: not OK to resolve until disposition changed manually.
> >                 
> >                 
> >                 
> >                 
> >               
> >             
> >             
> >               
> >                 
> >                 
> >               
> >               
> >               
> >                 
> >                   You are:
> >                   
> >                 
> >                 
> >                 
> >                 
> >                 
> >                 
> >                   
> >                   
> >                   Discussing: OK to resolve only if acknowledged
> >                   
> >                   or OK'd
> >                   last comment.
> >                   (Currently: OK.)
> >                   
> >                 
> >                 
> >                    Satisfied: OK to resolve any time, and own comments don't require acknowledgement.
> >                   
> >                 
> >                 
> >                    Blocking: not OK to resolve until disposition changed manually.
> >                 
> >                 
> >                    Withdrawn: dropped and resolved the discussion before it got started.
> >                   
> >                     This will resolve and hide the discussion.
> >                   
> >                 
> >                 
> >                 
> >               
> >             
> >           
> >           
> >             
> >               
> >                 
> >                   Done
> >                 
> >                 
> >                 Thanks for clarifying
</details>
Thanks for clarifying! I don't really know how replying works on reviewable. Please disregard the last comment. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2)*

**Comment by enochtsang** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[format.sh, line 3 at r3](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KU69_9Ke_VwIP4GW2Va:-KU69_9Ke_VwIP4GW2Vb:boni41i) ([raw file](https://github.com/ucsolarcarteam/backupcamera/blob/987128fbd85f87bea3d099143196d37aa014b5a8/format.sh#L3)):*
> ```Shell
> #!/bin/bash -e
> 
> astyle "*.h" "*.c" -r --options=astylerc
> ```

This needs to be changed to `*.cpp` instead of `*.c`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2)*

**Comment by enochtsang** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2#-KU69mYrTPdRr6NVpLw3:-KU69mYrTPdRr6NVpLw4:b-i6oo1j) (no related file):*
All the files in this repo need to be formatted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2)*

**Comment by bseto** [comment]
Reviewed 9 of 11 files at r4.
Review status: 10 of 12 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2)*

**Comment by bseto** [comment]
Reviewed 1 of 3 files at r1, 2 of 11 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/backupcamera/2)*

**Pull request merged**
